language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7

env: 
  - PARSE_RESOURCE_APPLICATION_ID=FKEzdzDgEyghLDFgIVHYJehVlWpfVtUmEv4MUEkJ PARSE_RESOURCE_MASTER_KEY=bOYO7usWbrcIbL5L5bPzlYrSonQRvwJecC1XLsuN

before_install:
  - gem install json